<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GenderSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('genders')->insert([
        ["name" => "Abinary"],
        ["name" => "Agender"],
        ["name" => "Ambigender"],
        ["name" => "Androgyne"],
        ["name" => "Androgynos"],
        ["name" => "Androgynous"],
        ["name" => "Aporagender"],
        ["name" => "Autigender"],
        ["name" => "Bakla"],
        ["name" => "Bigender"],
        ["name" => "Binary"],
        ["name" => "Bissu"],
        ["name" => "Butch"],
        ["name" => "Calabai"],
        ["name" => "Calalai"],
        ["name" => "Cis"],
        ["name" => "Cisgender"],
        ["name" => "Cis female"],
        ["name" => "Cis male"],
        ["name" => "Cis man"],
        ["name" => "Cis woman"],
        ["name" => "Demi-boy"],
        ["name" => "Demiflux"],
        ["name" => "Demigender"],
        ["name" => "Demi-girl"],
        ["name" => "Demi-guy"],
        ["name" => "Demi-man"],
        ["name" => "Demi-woman"],
        ["name" => "Dual gender"],
        ["name" => "Endosex"],
        ["name" => "Eunuch"],
        ["name" => "Fa'afafine"],
        ["name" => "Female"],
        ["name" => "Female to male"],
        ["name" => "Femme"],
        ["name" => "FTM"],
        ["name" => "Gender bender"],
        ["name" => "Gender creative"],
        ["name" => "Gender diverse"],
        ["name" => "Gender gifted"],
        ["name" => "Genderfluid"],
        ["name" => "Genderflux"],
        ["name" => "Genderfuck"],
        ["name" => "Genderless"],
        ["name" => "Gendervague"],
        ["name" => "Gender nonconforming"],
        ["name" => "Genderqueer"],
        ["name" => "Gender questioning"],
        ["name" => "Gender variant"],
        ["name" => "Graygender"],
        ["name" => "Hijra"],
        ["name" => "Intergender"],
        ["name" => "Intersex"],
        ["name" => "Ipsogender"],
        ["name" => "Kathoey"],
        ["name" => "Male"],
        ["name" => "Male to female"],
        ["name" => "Man"],
        ["name" => "Man of trans experience"],
        ["name" => "Maverique"],
        ["name" => "MTF"],
        ["name" => "Multigender"],
        ["name" => "Muxe"],
        ["name" => "Neither"],
        ["name" => "Neurogender"],
        ["name" => "Neutrois"],
        ["name" => "Non-binary"],
        ["name" => "Non-binary transgender"],
        ["name" => "Omnigender"],
        ["name" => "Other"],
        ["name" => "Pangender"],
        ["name" => "Polygender"],
        ["name" => "Person of transgendered experience"],
        ["name" => "Queer"],
        ["name" => "Sekhet"],
        ["name" => "Third gender"],
        ["name" => "Trans"],
        ["name" => "Trans female"],
        ["name" => "Trans male"],
        ["name" => "Trans man"],
        ["name" => "Trans person"],
        ["name" => "Trans woman"],
        ["name" => "Transgender"],
        ["name" => "Transgender female"],
        ["name" => "Transgender male"],
        ["name" => "Transgender man"],
        ["name" => "Transgender person"],
        ["name" => "Transgender woman"],
        ["name" => "Transfeminine"],
        ["name" => "Transmasculine"],
        ["name" => "Transsexual"],
        ["name" => "Transsexual female"],
        ["name" => "Transsexual male"],
        ["name" => "Transsexual man"],
        ["name" => "Transsexual person"],
        ["name" => "Transsexual woman"],
        ["name" => "Travesti"],
        ["name" => "Trigender"],
        ["name" => "Tumtum"],
        ["name" => "Two spirit"],
        ["name" => "Vakasalewalewa"],
        ["name" => "Waria"],
        ["name" => "Winkte"],
        ["name" => "Woman"],
        ["name" => "Woman of trans experience"],
        ["name" => "X-gender"],
        ["name" => "Xenogender"]
        
        ]);
    }
}
