<?php

return [
    "Abinary",
    "Agender",
    "Ambigender",
    "Androgyne",
    "Androgynos",
    "Androgynous",
    "Aporagender",
    "Autigender",
    "Bakla",
    "Bigender",
    "Binary",
    "Bissu",
    "Butch",
    "Calabai",
    "Calalai",
    "Cis",
    "Cisgender",
    "Cis female",
    "Cis male",
    "Cis man",
    "Cis woman",
    "Demi-boy",
    "Demiflux",
    "Demigender",
    "Demi-girl",
    "Demi-guy",
    "Demi-man",
    "Demi-woman",
    "Dual gender",
    "Endosex",
    "Eunuch",
    "Fa'afafine",
    "Female",
    "Female to male",
    "Femme",
    "FTM",
    "Gender bender",
    "Gender creative",
    "Gender diverse",
    "Gender gifted",
    "Genderfluid",
    "Genderflux",
    "Genderfuck",
    "Genderless",
    "Gendervague",
    "Gender nonconforming",
    "Genderqueer",
    "Gender questioning",
    "Gender variant",
    "Graygender",
    "Hijra",
    "Intergender",
    "Intersex",
    "Ipsogender",
    "Kathoey",
    "Male",
    "Male to female",
    "Man",
    "Man of trans experience",
    "Maverique",
    "MTF",
    "Multigender",
    "Muxe",
    "Neither",
    "Neurogender",
    "Neutrois",
    "Non-binary",
    "Non-binary transgender",
    "Omnigender",
    "Other",
    "Pangender",
    "Polygender",
    "Person of transgendered experience",
    "Queer",
    "Sekhet",
    "Third gender",
    "Trans",
    "Trans female",
    "Trans male",
    "Trans man",
    "Trans person",
    "Trans woman",
    "Transgender",
    "Transgender female",
    "Transgender male",
    "Transgender man",
    "Transgender person",
    "Transgender woman",
    "Transfeminine",
    "Transmasculine",
    "Transsexual",
    "Transsexual female",
    "Transsexual male",
    "Transsexual man",
    "Transsexual person",
    "Transsexual woman",
    "Travesti",
    "Trigender",
    "Tumtum",
    "Two spirit",
    "Vakasalewalewa",
    "Waria",
    "Winkte",
    "Woman",
    "Woman of trans experience",
    "X-gender",
    "Xenogender"
];